# Generated by Django 5.2.7 on 2025-11-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_googleaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleaccount',
            name='photo_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
